config/routes.rb
Rails.application.routes.draw do
	resources :sessions, only: [:new, :create, :destroy]
	
	get 'signup', to: 'users#new', as: 'signup'
	get 'login', to: 'sessions#new', as: 'login'
	get 'logout', to: 'sessions#destroy', as: 'logout'
	get 'list', to: 'users#show', as: 'list'
	get 'dashboard', to: 'page#dashboard', as: 'dashboard'
	patch 'edit' => 'cards#update', as: 'edit'

  resources :users
  
  resources :cards
  	
  	get 'page/index'
	root 'page#index'

end

app/models/card.rb
class Card < ActiveRecord::Base
	validates :recipe_name, presence: true, length: { minimum: 5 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  
  	def to_s 
	  "#{first_name} #{last_name}"
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
  protect_from_forgery with: :exception
  
   def authenticate
	    if session['user_id'].nil?
		    flash[:notice] = 'You must login.'
	      redirect_to login_path
	   end
   end
  
  private
  
  def current_user
	  User.where(id: session[:user_id]).first
end
	helper_method :current_user
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
	def index
		@cards = Card.all
	end 
	
	
	def show
		@card = Card.find(params[:id])
	end
	
	def new
		@card = Card.new
	end 
	
	def edit
		@card = Card.find(params[:id])
	end 
	
	def create
		@card = Card.new(card_params)
		
		if @card.save
			flash[:notice] = 'Recipe successfully created.'
			redirect_to @card
		else
			render 'new'
		end
	end 
	
	def update
		@card = Card.find(params[:id])
		
		if @card.update(card_params)
			flash[:notice] = 'Recipe successfully updated.'
			redirect_to @card 
		else
			render 'edit'
		end
	end 
	
	def destroy
		@card = Card.find(params[:id])
		@card.destroy
		
		flash[:notice] = 'Recipe successfully deleted.'
		redirect_to cards_path
	end	
	
	private
	
		def card_params
			params.require(:card).permit(:recipe_name, :instruction, :portion, :variation, :storage, :comment)
		end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
 
  def dashboard
  end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	before_filter :authenticate, :only=> [:destroy]
	
  def new
  end

  def create
	  user = User.find_by_email(params[:email])
	  if user && user.authenticate(params[:password])
		  session[:user_id] = user.id 
		  redirect_to dashboard_path
	  end
	  if session[:user_id].nil?
	  	flash[:notice] = 'Email or password failed.'
	  	# to set the first user, comment out the line below and go to http://localhost:3000/users/new, then uncomment it again and you are good to go.
	  	redirect_to login_path
	  end
  end

  def destroy
	  session[:user_id] = nil 
	  redirect_to login_path, notice: 'Logged out.'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/_form.html.erb
<%= form_for :card, url: cards_path do |f| %>

	<% if @card.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@card.errors.count, "error") %> prohibited
        this recipe from being saved:
      </h2>
      <ul>
        <% @card.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

	
	<p>
		<%= f.label :recipe_name %><br>
		<%= f.text_field :recipe_name %>
	</p>
	
	<p>
		<%= f.label :instruction %><br>
		<%= f.text_area :instruction %>
	</p>
	
	<p>
		<%= f.label :portion %><br>
		<%= f.text_field :portion %>
	</p>

	<p>
		<%= f.label :variation %><br>
		<%= f.text_field :variation %>
	</p>

	<p>
		<%= f.label :storage %><br>
		<%= f.text_field :storage %>
	</p>

	<p>
		<%= f.label :comment %><br>
		<%= f.text_area :comment %>
	</p>

	
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/cards/_form_update.html.erb
<%= form_for :card, url: card_path(@card), method: :patch do |f| %>

	<% if @card.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@card.errors.count, "error") %> prohibited
        this recipe from being saved:
      </h2>
      <ul>
        <% @card.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

	
	<p>
		<%= f.label :recipe_name %><br>
		<%= f.text_field :recipe_name %>
	</p>
	
	<p>
		<%= f.label :instruction %><br>
		<%= f.text_area :instruction %>
	</p>
	
	<p>
		<%= f.label :portion %><br>
		<%= f.text_field :portion %>
	</p>

	<p>
		<%= f.label :variation %><br>
		<%= f.text_field :variation %>
	</p>

	<p>
		<%= f.label :storage %><br>
		<%= f.text_field :storage %>
	</p>

	<p>
		<%= f.label :comment %><br>
		<%= f.text_area :comment %>
	</p>

	
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing card</h1>
 
<%= render 'form_update' %>
 
<%= link_to 'View all recipes', cards_path %>

app/views/cards/index.html.erb
<h1>List of recipes</h1>

<table id="show">
	<tr>
		<th>recipe</th>
		<th>instruction</th>
		<th colspan="3">Function</th>
	</tr>

	<% @cards.each do |card| %>
		<tr>
			<td><%= card.recipe_name %></td>
			<td><%= card.instruction %></td>
			
			<td><%= link_to 'Show', card_path(card) %></td>
			<td><%= link_to 'Edit', edit_card_path(card) %></td>
			<td><%= link_to 'Destroy', card_path(card), method: :delete, data: { confirm: 'Are you sure you want to delete this recipe entirely? This action is not undoable!' } %></td>
		</tr>
	<% end %>
</table>
<br>
<%= link_to 'New recipe', new_card_path %> or
<%= link_to 'Users', users_path %>

app/views/cards/new.html.erb
<h1>New recipe</h1>

<%= render 'form' %>

<%= link_to 'View all recipes', cards_path %>

app/views/cards/show.html.erb
<table id="show">

<th>
	<b>Recipe name:</b></th>
	<td>
	<%= @card.recipe_name %>
	</td>
	
</table>
</p>

	<b>Instruction:</b>
	
	<table id="show">
<div id="wrap">
	

	<td>
	<%= @card.instruction %>
	</td>
<td>

	<b>Portion:</b>
	<%= @card.portion %>

<p>
	<b>Variation:</b>
	<%= @card.variation %>
</p>

<p>
	<b>Storage:</b>
	<%= @card.storage %>
</p>

<p>
	<b>Comment:</b>
	<%= @card.comment %>
</p>
</td>
</div>
</table>

<br><br>

<%= link_to 'Edit recipe', edit_card_path(@card) %> or
<%= link_to 'View all recipes', cards_path %> or
<%= link_to 'New recipe', new_card_path %> or
<%= link_to 'Users', users_path %>

app/views/layouts/_footer.html.erb
<footer id="page_footer">
	<ul>
		<li><%= link_to "Contact", "" %></li>
		<li><%= link_to "About", "" %></li>
	</ul>
	<p>&copy; 2015 Andres Orjuela. All rights reserved.</p>
</footer>

app/views/layouts/_header.html.erb
<header id="page_header" role="banner">

	<%= link_to(image_tag("the_special_miami_logo.png", alt: "The Special", id: "logo"), root_url, title: "Dashboard") %>
		
		<div id="user">
		<% if current_user %>
			Logged in as <%= current_user.email %>
			<%= link_to "Logout", logout_path %>
		<% end %>
	</div>

		
		<h3>Welcome to Andres's database of recipes.</h3>
		
	

</header>

	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
  <title>Recipe</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render 'layouts/header' %>
	
	
	
	<div id="main">
		<%= yield %>
	</div>
	
	<div id="flash">
	<% flash.each do |key, value| %>
		<%= content_tag(:div, class: "alert alert-#{key}") do %>
			<p><%= value %></p>
		<% end %>
	<% end %>
	</div>
		
	<%= render 'layouts/footer' %>


</body>
</html>

app/views/page/dashboard.html.erb
<h1>Dashboard</h1>

<%= link_to 'Users', users_path %> or <%= link_to 'Recipes', cards_path %>

app/views/page/index.html.erb
<div id="login">
	<%= link_to "Login", login_path %>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>List of registered users</h1>

<table id="show">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %> or <%= link_to 'Recipes', cards_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<table id="show">

<th>


  <strong>First name:</strong></th>
	<td>
  <%= @user.first_name %>
	</td>
	
</table>

<p>

  
  	<table id="show">
<div id="wrap">
	<th>
		<strong>Last name:</strong>
	</th>

	<td>
  
  <%= @user.last_name %>
  </td>
</table>
<table id="show">
<th>
  <strong>Email:</strong></th>
  <td>
  <%= @user.email %></td>
</p>
</table>



<br><br>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>